dist: xenial
group: travis_latest

sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  fast_finish: true

  include:
    # lint
    - python: "3.7"
      stage: lint
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=manifest

    # test
    - python: "pypy"
      stage: test
      dist: trusty
      env: TOXENV=pypy-twisted
    - python: "2.7"
      env: TOXENV=py27-twisted
    - python: "3.5"
      env: TOXENV=py35-twisted
    - python: "3.5"
      env: TOXENV=py35-aiohttp
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36-twisted
    - python: "3.6"
      env: TOXENV=py36-aiohttp
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37-twisted
    - python: "3.7"
      env: TOXENV=py37-aiohttp
    - python: "3.7"
      env: TOXENV=py37
    # - python: "pypy3"
    #   dist: trusty
    #   env: TOXENV=pypy3-twisted
    # - python: "pypy3"
    #   dist: trusty
    #   env: TOXENV=pypy3-aiohttp
    - python: "pypy3"
      dist: trusty
      env: TOXENV=pypy3

    # Prevent breakage by a new releases
    - python: "3.6-dev"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37

    # Docs
    - python: "3.7"
      stage: docs
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=pypi-description

  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"


install:
  - pip install -U tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
